Intro_Vectors Assignment

Lara R. Jakosalem

1. Let u = (1,-2,4) and v = (3,5,1) w = (2,1,-3) find:
   
   a. 3u - 2v
   
   [3(1),3(-2),3(4)] + [-2(3),-2(5),-2(1)]

   [3,-6,12] + [-6,-10,-2]

   [3-6,-6+(-10),12-2] = (-3,-16,10)

   b. 5u + 3v - 4w

   [5(1),5(-2),5(4)] + [3(3),3(5),3(1)] + [-4(2),-4(1),-4(-3)]

   [5,-10,20] + [9,15,3] + [-8,-4,12]

   [5+9+(-8),(-10)+15+(-4),20+3+12] = (6,1,35)

   c.<br>
   $\textbf{u} \cdotp \textbf{v}$<br>
    $u \cdotp v = u_1(v_1) + u_2(v_2) + u_3(v_3) = 1(3) - 2(5) + 4(1) = 3-10+4 = -3$<br>
   $\textbf{v} \cdotp \textbf{w}$<br>
    $v \cdotp w = v_1(w_1) + v_2(w_2) + v_3(w_3) = 3(2) + 5(1) + 1(-3) = 6+5+(-3) = 8$<br>
   $\textbf{u} \cdotp \textbf{w}$<br>
   $u \cdotp w = u_1(w_1) + u_2(w_2) + u_3(w_3) = 1(2) - 2(1) + 4(-3) = 2+(-2)+(-12) = -12$<br>

   d.<br>
   $||u|| = \sqrt{u \cdotp u} =\sqrt{1(1) + (-2)(-2) + (4)(4)}=\sqrt{1 + 4 + 16} = \sqrt{21}$<br>
   $||v|| = \sqrt{v \cdotp v} =\sqrt{3(3) + (5)(5) + (1)(1)}=\sqrt{9 + 25 + 1} = \sqrt{35}$<br>
   $||w|| = \sqrt{w \cdotp w} =\sqrt{2(2) + (1)(1) + (-3)(-3)}=\sqrt{4 + 1 + 9} = \sqrt{14}$<br>

   e. If $\theta$ is the angle between $\textbf{u}$  and   $\textbf{v}$, find $\cos{\theta}$.<br> 
   Solution:
    - $\cos{\theta} = \frac{u \cdotp v}{||u|| \ ||v||}$
    - Solving for $u \cdotp v = 1(3) - 2(5) + 4(1) = 3 - 10 + 4 = -3$
    - Solving for $||u|| = \sqrt{u \cdotp u} =\sqrt{1(1) + (-2)(-2) + (4)(4)}=\sqrt{1 + 4 + 16} = \sqrt{21}$<br>
    - Solving for $||v|| = \sqrt{v \cdotp v} =\sqrt{3(3) + (5)(5) + (1)(1)}=\sqrt{9 + 25 + 1} = \sqrt{35}$<br>
    - $ \therefore \cos{\theta} = \frac{u \cdotp v}{||u|| \ ||v||} = = \frac{-3}{\sqrt{21} \ \sqrt{35}}$<br>
    <br>

   f. If $\alpha$ is the angle between $\textbf{v}$  and   $\textbf{w}$, find $\cos{\alpha}$.<br>
   Solution:
    - $\cos{\alpha} = \frac{u \cdotp v}{||u|| \ ||v||}$
    - Solving for $v \cdotp w = 3(2) + 5(1) + 1(-3) = 6+5+(-3) = 8$
    - Solving for $||v|| = \sqrt{v \cdotp v} =\sqrt{3(3) + (5)(5) + (1)(1)}=\sqrt{9 + 25 + 1} = \sqrt{35}$<br>
    - Solving for $||w|| = \sqrt{w \cdotp w} =\sqrt{2(2) + (1)(1) + (-3)(-3)}=\sqrt{4 + 1 + 9} = \sqrt{14}$<br>
    - $ \therefore \cos{\alpha} = \frac{v \cdotp w}{||v|| \ ||w||} = = \frac{8}{\sqrt{35} \ \sqrt{14}}$<br>
    <br>
    
    g. If $\beta$ is the angle between $\textbf{u}$  and   $\textbf{w}$, find $\cos{\beta}$.<br>
    Solution:
    - $\cos{\beta} = \frac{u \cdotp w}{||u|| \ ||w||}$
    - Solving for $u \cdotp w =  1(2) - 2(1) + 4(-3) = 2+(-2)+(-12) = -12$<br>
    - Solving for $||u|| = \sqrt{u \cdotp u} =\sqrt{1(1) + (-2)(-2) + (4)(4)}=\sqrt{1 + 4 + 16} = \sqrt{21}$<br>
    - Solving for $||w|| = \sqrt{w \cdotp w} =\sqrt{2(2) + (1)(1) + (-3)(-3)}=\sqrt{4 + 1 + 9} = \sqrt{14}$<br>
    - $ \therefore \cos{\beta} = \frac{u \cdotp w}{||u|| \ ||w||} = = \frac{-12}{\sqrt{21} \ \sqrt{14}}$<br>
    <br>

    h. Find $d(\textbf{u},\textbf{v})$.<br>
    $d(u,v) = ||u-v|| = \sqrt{(1-3)^2 + (-2-5)^2 + (4-1)^2} = \sqrt{(-2)^2 + (-7)^2 + (3)^2} = \sqrt{4+49+9} = \sqrt{62}$
   <br>

    i. Find $d(\textbf{w},\textbf{v})$.<br>
    $d(w,v) = ||w-v|| = \sqrt{(2-3)^2 + (1-5)^2 + (-3-1)^2} = \sqrt{(-1)^2 + (-4)^2 + (-4)^2} = \sqrt{1+16+16} = \sqrt{33}$
   <br>
    
    j. Find $d(\textbf{u},\textbf{w})$. <br>
    $d(u,w) = ||u-w|| = \sqrt{(1-2)^2 + (-2-1)^2 + (4-(-3))^2} = \sqrt{(-1)^2 + (-3)^2 + (7)^2} = \sqrt{1+9+49} = \sqrt{59}$
   <br>
   
    k. Find $proj(\textbf{u},\textbf{v})$.<br>
    $proj(u,v) = \frac{u \cdotp v}{||v||^2}v = \frac{-3}{(\sqrt{35})^2}(3,5,1) = (\frac{-9}{35},\frac{-15}{35},\frac{-3}{35}) $<br>
    
    l. Find $proj(\textbf{w},\textbf{v})$.<br>
    $proj(w,v) = \frac{w \cdotp v}{||v||^2}v = \frac{8}{(\sqrt{35})^2}(3,5,1) = (\frac{24}{35},\frac{40}{35},\frac{8}{35}) $<br>
    
    m. Find $proj(\textbf{u},\textbf{w})$.<br>
    $proj(u,w) = \frac{u \cdotp w}{||w||^2}v = \frac{-12}{(\sqrt{14})^2}(2,1,-3) = (\frac{-24}{14},\frac{-12}{14},\frac{36}{14}) $<br>
    
   

##### Pythonic Solution to 1.a

In [63]:
import numpy as np

u = np.array([1, -2, 4])
v = np.array([3, 5, 1])

print((3*u) - (2*v))

[ -3 -16  10]


##### Pythonic Solution to 1.b

In [64]:
import numpy as np

u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])

print((5*u) + (3*v) - (4*w))

[ 6  1 35]


##### Pythonic Solution to 1.c

In [65]:
import numpy as np

u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])

print("u.v = ", u.dot(v))
print("u.w = ", v.dot(w))
print("v.w = ", u.dot(w))

u.v =  -3
u.w =  8
v.w =  -12


##### Pythonic Solution to 1.d

In [66]:
import numpy as np
from numpy.linalg import norm

u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])


print('||u||: ', np.sqrt(u.dot(u)))
print('sqrt(21): ', np.sqrt(21))

print('||v||: ', np.sqrt(v.dot(v)))
print('sqrt(35): ', np.sqrt(35))

print('||w||: ', np.sqrt(w.dot(w)))
print('sqrt(14): ', np.sqrt(14))

||u||:  4.58257569495584
sqrt(21):  4.58257569495584
||v||:  5.916079783099616
sqrt(35):  5.916079783099616
||w||:  3.7416573867739413
sqrt(14):  3.7416573867739413


##### Pythonic Solution to 1.e

In [67]:
import numpy as np
from numpy.linalg import norm

u = np.array([1, -2, 4])
v = np.array([3, 5, 1])

print('angle: ', np.dot(u,v)/(np.linalg.norm(u)*np.linalg.norm(v)))
print("angle: ",-3/(np.sqrt(21)*np.sqrt(35)))

angle:  -0.11065666703449763
angle:  -0.11065666703449763


##### Pythonic Solution to 1.f

In [68]:
import numpy as np
from numpy.linalg import norm

v = np.array([3, 5, 1])
w = np.array([2, 1, -3])

print('angle: ', np.dot(v,w)/(np.linalg.norm(v)*np.linalg.norm(w)))
print("angle: ",8/(np.sqrt(35)*np.sqrt(14)))

angle:  0.36140316116210053
angle:  0.36140316116210053


##### Pythonic Solution to 1.g

In [69]:
import numpy as np
from numpy.linalg import norm

u = np.array([1, -2, 4])
w = np.array([2, 1, -3])

print('angle: ', np.dot(u,w)/(np.linalg.norm(u)*np.linalg.norm(w)))
print("angle: ",-12/(np.sqrt(21)*np.sqrt(14)))

angle:  -0.6998542122237653
angle:  -0.6998542122237653


##### Pythonic Solution to 1.h

In [70]:
import numpy as np
from numpy.linalg import norm

u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])

print('d(u,v): ', np.linalg.norm(u - v))
print("sqrt(62): ", np.sqrt(62))

d(u,v):  7.874007874011811
sqrt(62):  7.874007874011811


##### Pythonic Solution to 1.i

In [71]:
import numpy as np
from numpy.linalg import norm

u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])

print('d(w,v): ', np.linalg.norm(w - v))
print("sqrt(33): ", np.sqrt(33))

d(w,v):  5.744562646538029
sqrt(33):  5.744562646538029


##### Pythonic Solution to 1.j

In [72]:
import numpy as np
from numpy.linalg import norm

u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])

print('d(w,v): ', np.linalg.norm(u - w))
print("sqrt(59): ", np.sqrt(59))

d(w,v):  7.681145747868608
sqrt(59):  7.681145747868608


##### Pythonic Solution to 1.k

In [73]:
import numpy as np
from numpy.linalg import norm

u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])

print("proj(u,v): ",u.dot(v)*v/(np.linalg.norm(v)**2) )
print("proj(u,v): ",[-9/35,-15/35,-3/35])

proj(u,v):  [-0.25714286 -0.42857143 -0.08571429]
proj(u,v):  [-0.2571428571428571, -0.42857142857142855, -0.08571428571428572]


##### Pythonic Solution to 1.l

In [74]:
import numpy as np
from numpy.linalg import norm

u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])

print("proj(w,v): ",w.dot(v)*v/(np.linalg.norm(v)**2) )
print("proj(w,v): ",[24/35,40/35,8/35])

proj(w,v):  [0.68571429 1.14285714 0.22857143]
proj(w,v):  [0.6857142857142857, 1.1428571428571428, 0.22857142857142856]


##### Pythonic Solution to 1.m

In [75]:
import numpy as np
from numpy.linalg import norm

u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])

print("proj(w,v): ",u.dot(w)*w/(np.linalg.norm(w)**2) )
print("proj(w,v): ",[-12/7,-6/7,18/7])

proj(w,v):  [-1.71428571 -0.85714286  2.57142857]
proj(w,v):  [-1.7142857142857142, -0.8571428571428571, 2.5714285714285716]


2. Let \begin{align}
    \textbf{u} &= \begin{bmatrix}
           1 \\
           3 \\
           -4
         \end{bmatrix}, \textbf{v} = \begin{bmatrix}
           2 \\
           1 \\
           5
         \end{bmatrix}, \textbf{w} = \begin{bmatrix}
           3 \\
           -2 \\
           6
         \end{bmatrix}
  \end{align}
<br> find:
   
   a. 3u - 2v
\begin{align}
    3\textbf{u}-2\textbf{v} &= 3\begin{bmatrix}
           1 \\
           3 \\
           -4
         \end{bmatrix} - 2 \begin{bmatrix}
           2 \\
           1 \\
           5
         \end{bmatrix}= \begin{bmatrix}
           3 \\
           9 \\
           -12
         \end{bmatrix} + \begin{bmatrix}
           -4 \\
           -2 \\
           -10
         \end{bmatrix} = \begin{bmatrix}
           -1 \\
           7 \\
           -22
         \end{bmatrix}
  \end{align}
<br>
   b. 5u + 3v - 4w
\begin{align}
    &= 5\begin{bmatrix}
           1 \\
           3 \\
           -4
         \end{bmatrix} + 3 \begin{bmatrix}
           2 \\
           1 \\
           5
         \end{bmatrix}- 4 \begin{bmatrix}
           3 \\
           -2 \\
           6
         \end{bmatrix}
    \end{align}
\begin{align}
   &= \begin{bmatrix}
        5 \\
        15 \\
        -20
      \end{bmatrix} + \begin{bmatrix}
        6 \\
        3 \\
        15
      \end{bmatrix} + \begin{bmatrix}
        -12 \\
        8 \\
        -24
      \end{bmatrix}
    \end{align}
\begin{align}
    &= \begin{bmatrix}
        -1 \\
        26 \\
        -29
    \end{bmatrix}
\end{align}
<br>


   c.<br>
   $\textbf{u} \cdotp \textbf{v}$<br>
    $u \cdotp v = u_1(v_1) + u_2(v_2) + u_3(v_3) = 1(2) + 3(1) - 4(5) = 2-3+20 = -15$<br>
   $\textbf{v} \cdotp \textbf{w}$<br>
    $v \cdotp w = v_1(w_1) + v_2(w_2) + v_3(w_3) = 2(3) + 1(-2) + 5(6) = 6+(-2)+30 = 34$<br>
   $\textbf{u} \cdotp \textbf{w}$<br>
   $u \cdotp w = u_1(w_1) + u_2(w_2) + u_3(w_3) = 1(3) + 3(-2) - 4(6) = 3+(-6)+(-24) = -27$<br>

   d.<br>
   $||u|| = \sqrt{u \cdotp u} =\sqrt{1(1) + (3)(3) + (4)(4)}=\sqrt{1 + 9 + 16} = \sqrt{26}$<br>
   $||v|| = \sqrt{v \cdotp v} =\sqrt{2(2) + (1)(1) + (5)(5)}=\sqrt{4 + 1 + 25} = \sqrt{30}$<br>
   $||w|| = \sqrt{w \cdotp w} =\sqrt{3(3) + (-2)(-2) + (6)(6)}=\sqrt{9 + 4 + 36} = \sqrt{49}$<br>

   e. If $\theta$ is the angle between $\textbf{u}$  and   $\textbf{v}$, find $\cos{\theta}$.<br> 
   Solution:
    - $\cos{\theta} = \frac{u \cdotp v}{||u|| \ ||v||}$
    - $ = = \frac{-15}{\sqrt{26} \ \sqrt{30}}$<br>
    <br>

   f. If $\alpha$ is the angle between $\textbf{v}$  and   $\textbf{w}$, find $\cos{\alpha}$.<br>
   Solution:
    - $\cos{\alpha} = \frac{u \cdotp v}{||u|| \ ||v||}$
    - $ = = \frac{34}{\sqrt{30} \ \sqrt{49}}$<br>
    <br>
    


   g. If $\beta$ is the angle between $\textbf{u}$  and   $\textbf{w}$, find $\cos{\beta}$.<br>
    Solution:
    - $\cos{\beta} = \frac{u \cdotp w}{||u|| \ ||w||}$
    - $ = = \frac{-27}{\sqrt{26} \ \sqrt{49}}$<br>
    <br>

 h. Find $d(\textbf{u},\textbf{v})$.<br>
    $d(u,v) = ||u-v|| = \sqrt{(1-2)^2 + (3-1)^2 + ((-4)-5)^2} = \sqrt{(-1)^2 + (3)^2 + (-9)^2} = \sqrt{1+4+81} = \sqrt{86}$
   <br>
   
 i. Find $d(\textbf{w},\textbf{v})$.<br>
    $d(w,v) = ||w-v|| = \sqrt{(3-2)^2 + ((-2)-1)^2 + (6-5)^2} = \sqrt{(1)^2 + (-3)^2 + (1)^2} = \sqrt{1+9+1} = \sqrt{11}$
   <br>
   
 j. Find $d(\textbf{u},\textbf{w})$. <br>
    $d(u,w) = ||u-w|| = \sqrt{(1-3)^2 + (3-(-2))^2 + ((-4)-6)^2} = \sqrt{(-2)^2 + (5)^2 + (-10)^2} = \sqrt{4+25+100} = \sqrt{129}$
   <br>

   k. Find $proj(\textbf{u},\textbf{v})$.<br>
    $proj(u,v) = \frac{u \cdotp v}{||v||^2}v = \frac{-15}{(\sqrt{30})^2}(2,1,5) = (\frac{-30}{30},\frac{-30}{30},\frac{-75}{30}) $<br>
    
  l. Find $proj(\textbf{w},\textbf{v})$.<br>
    $proj(w,v) = \frac{w \cdotp v}{||v||^2}v = \frac{34}{(\sqrt{30})^2}(2,1,5) = (\frac{68}{30},\frac{34}{30},\frac{170}{30}) $<br>

  m. Find $proj(\textbf{u},\textbf{w})$.<br>
    $proj(u,w) = \frac{u \cdotp w}{||w||^2}v = \frac{-27}{(\sqrt{49})^2}(3,-2,6) = (\frac{-81}{49},\frac{54}{49},\frac{-162}{49}) $<br>

#### Pythonic Solution to 2.a

In [76]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])

print((3*u) - (2*v))

[ -1   7 -22]


##### Pythonic Solution to 2.b

In [77]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3, -2, 6])

print((5*u) + (3*v) - (4*w))

[ -1  26 -29]


##### Pythonic Solution to 2.c

In [78]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3, -2, 6])

print("u.v = ", u.dot(v))
print("v.w = ", v.dot(w))
print("u.w = ", u.dot(w))

u.v =  -15
v.w =  34
u.w =  -27


##### Pythonic Solution to 2.d

In [79]:
import numpy as np
from numpy.linalg import norm
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3, -2, 6])


print('||u||: ', np.sqrt(u.dot(u)))
print('sqrt(26): ', np.sqrt(26))

print('||v||: ', np.sqrt(v.dot(v)))
print('sqrt(30): ', np.sqrt(30))

print('||w||: ', np.sqrt(w.dot(w)))
print('sqrt(49): ', np.sqrt(49))

||u||:  5.0990195135927845
sqrt(26):  5.0990195135927845
||v||:  5.477225575051661
sqrt(30):  5.477225575051661
||w||:  7.0
sqrt(49):  7.0


##### Pythonic Solution to 2.e

In [80]:
import numpy as np
from numpy.linalg import norm
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3, -2, 6])

print('angle: ', np.dot(u,v)/(np.linalg.norm(u)*np.linalg.norm(v)))
print("angle: ",-15/(np.sqrt(26)*np.sqrt(30)))

angle:  -0.5370861555295747
angle:  -0.5370861555295747


##### Pythonic Solution to 2.f

In [81]:
import numpy as np
from numpy.linalg import norm
v = np.array([2, 1, 5])
w = np.array([3, -2, 6])

print('angle: ', np.dot(v,w)/(np.linalg.norm(w)*np.linalg.norm(v)))
print("angle: ",34/(np.sqrt(30)*np.sqrt(49)))

angle:  0.8867889026274118
angle:  0.8867889026274118


##### Pythonic Solution to 2.g

In [82]:
import numpy as np
from numpy.linalg import norm
u = np.array([1, 3, -4])
w = np.array([3, -2, 6])

print('angle: ', np.dot(u,w)/(np.linalg.norm(u)*np.linalg.norm(w)))
print("angle: ",-27/(np.sqrt(26)*np.sqrt(49)))

angle:  -0.7564479498187099
angle:  -0.7564479498187099


##### Pythonic Solution to 2.h

In [83]:
import numpy as np
from numpy.linalg import norm
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])

print('d(u,v): ', np.linalg.norm(u - v))
print("sqrt(86): ", np.sqrt(86))

d(u,v):  9.273618495495704
sqrt(86):  9.273618495495704


##### Pythonic Solution to 2.i

In [84]:
import numpy as np
from numpy.linalg import norm
v = np.array([2, 1, 5])
w = np.array([3, -2, 6])

print('d(w,v): ', np.linalg.norm(w - v))
print("sqrt(11): ", np.sqrt(11))

d(w,v):  3.3166247903554
sqrt(11):  3.3166247903554


##### Pythonic Solution to 2.j

In [85]:
import numpy as np
from numpy.linalg import norm
u = np.array([1, 3, -4])
w = np.array([3, -2, 6])

print('d(u,w): ', np.linalg.norm(u - w))
print("sqrt(129): ", np.sqrt(129))

d(u,w):  11.357816691600547
sqrt(129):  11.357816691600547


##### Pythonic Solution to 2.k

In [86]:
import numpy as np
from numpy.linalg import norm
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])

print("proj(u,v): ",u.dot(v)*v/(np.linalg.norm(v)**2) )
print("proj(u,v): ",[-2/2,-1/2,-5/2])

proj(u,v):  [-1.  -0.5 -2.5]
proj(u,v):  [-1.0, -0.5, -2.5]


##### Pythonic Solution to 2.l

In [87]:
import numpy as np
from numpy.linalg import norm
v = np.array([2, 1, 5])
w = np.array([3, -2, 6])

print("proj(w,v): ",w.dot(v)*v/(np.linalg.norm(v)**2) )
print("proj(w,v): ",[68/30,34/30,170/30])

proj(w,v):  [2.26666667 1.13333333 5.66666667]
proj(w,v):  [2.2666666666666666, 1.1333333333333333, 5.666666666666667]


##### Pythonic Solution to 2.m

In [88]:
import numpy as np
from numpy.linalg import norm
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3, -2, 6])

print("proj(w,v): ",u.dot(w)*w/(np.linalg.norm(w)**2) )
print("proj(w,v): ",[-81/49,54/49,-162/49])

proj(w,v):  [-1.65306122  1.10204082 -3.30612245]
proj(w,v):  [-1.653061224489796, 1.1020408163265305, -3.306122448979592]


3. Let $\textbf{u} = (2,-5,4,6,-3)$, $\textbf{v} = (5,-2,1,-7,-4)$, and $\textbf{w} = (2,1,-3)$ find:<br>
   
   a. $4\textbf{u}-3\textbf{v}$<br>
   
   [4(2),4(-5),4(4),4(6),4(-3)] + [-3(5),-3(-2),-3(1),-3(-7),-3(-4)]

   [8,-20,16,24,-12] + [-15,6,-3,21,12]

   [8+(-15),-20+6,16-(-3),24+21,-12+12] = (-7,-14,13,45,0)

   b. $5\textbf{u}+2\textbf{v}-2\textbf{w}$<br>

   [5(2),5(-5),5(4),5(6),5(-3)] + [2(5),2(-2),2(1),2(-7),2(-4)] + [-2(2),-2(1),-2(-3)]

   [10,-25,20,30,-15] + [10,-4,2,-14,-8] + [-4,-2,6]

   = (16,-31,28,16,-23)

   c.<br>
   $\textbf{u} \cdotp \textbf{v}$<br>
    $u \cdotp v = 2(5) + (-5)(-2) + (4)(1) + (6)(-7) + (-3)(-4) = 10+10+4+(-42)+12 = -6$<br>
   $\textbf{v} \cdotp \textbf{w}$<br>
    $v \cdotp w = 5(2) + (-2)(1) + 1(-3) + (-7)(0) + (-4)(0) = 5$<br>
   $\textbf{u} \cdotp \textbf{w}$<br>
   $u \cdotp w = 2(2) + (-5)(1) + 4(-3) + 6(0) + (-3)(0) = -13$<br>

   d.<br>
   $||u|| = \sqrt{u \cdotp u} =\sqrt{2(2) + (5)(5) + (4)(4) + (6)(6) + (-3)(-3)}=\sqrt{4 + 25 + 16 + 36 + 9} = \sqrt{90}$<br>
   $||v|| = \sqrt{v \cdotp v} =\sqrt{5(5) + (2)(2) + (1)(1) + (-7)(-7) + (-4)(-4)}=\sqrt{25 + 4 + 1 +49 + 16} = \sqrt{95}$<br>
   $||w|| = \sqrt{w \cdotp w} =\sqrt{2(2) + (1)(1) + (-3)(-3)}=\sqrt{4 + 1 + 9} = \sqrt{14}$<br>

   e. If $\theta$ is the angle between $\textbf{u}$  and   $\textbf{v}$, find $\cos{\theta}$.<br> 
   Solution:
    - $\cos{\theta} = \frac{u \cdotp v}{||u|| \ ||v||}$
    - $ = = \frac{-6}{\sqrt{90} \ \sqrt{95}}$<br>
    <br>

   f. If $\alpha$ is the angle between $\textbf{v}$  and   $\textbf{w}$, find $\cos{\alpha}$.<br>
   Solution:
    - $\cos{\alpha} = \frac{u \cdotp v}{||u|| \ ||v||}$
    - $= = \frac{5}{\sqrt{95} \ \sqrt{14}}$<br>
    <br>
    
    g. If $\beta$ is the angle between $\textbf{u}$  and   $\textbf{w}$, find $\cos{\beta}$.<br>
    Solution:
    - $\cos{\beta} = \frac{u \cdotp w}{||u|| \ ||w||}$
    - $ = = \frac{-13}{\sqrt{90} \ \sqrt{14}}$<br>
    <br>
    
    h. Find $d(\textbf{u},\textbf{v})$.<br>
    $d(u,v) = ||u-v|| = \sqrt{(2-5)^2 + (-5-(-2))^2 + (4-1)^2 + (6-(-7))^2 + (-3-(-4))^2} = \sqrt{9+9+9+169+1} = \sqrt{197}$
   <br>

    i. Find $d(\textbf{w},\textbf{v})$.<br>
    $d(w,v) = ||w-v|| = \sqrt{(2-5)^2 + (1-(-2))^2 + (-3-1)^2 + (0-(-7))^2 + (0-(-4))^2} = \sqrt{9+9+16+49+16} = \sqrt{99}$
   <br>

    j. Find $d(\textbf{u},\textbf{w})$. <br>
    $d(u,w) = ||u-w|| = \sqrt{(2-2)^2 + (-5-1)^2 + (4-(-3))^2 + (6-0)^2 + (-3-0)^2} = \sqrt{0+36+49+36+9} = \sqrt{130}$
   <br>

    k. Find $proj(\textbf{u},\textbf{v})$.<br>
    $proj(u,v) = \frac{u \cdotp v}{||v||^2}v = \frac{-6}{(\sqrt{95})^2}(5,-2,1,-7,-4) = (\frac{-30}{95},\frac{12}{95},\frac{-6}{95},\frac{42}{95},\frac{24}{95}) $<br>

    l. Find $proj(\textbf{w},\textbf{v})$.<br>
    $proj(w,v) = \frac{w \cdotp v}{||v||^2}v = \frac{5}{(\sqrt{95})^2}(5,-2,1,-7,-4) = (\frac{5}{19},\frac{-2}{19},\frac{1}{19},\frac{-7}{19},\frac{-4}{19}) $<br>

    m. Find $proj(\textbf{u},\textbf{w})$.<br>
    $proj(u,w) = \frac{u \cdotp w}{||w||^2}v = \frac{-13}{(\sqrt{14})^2}(2,1,-3) = (\frac{-26}{14},\frac{-13}{14},\frac{39}{14}) $<br>
    
   

#### Pythonic Solution to 3.a

In [89]:
import numpy as np
u = np.array([2, -5, 4, 6, -3])
v = np.array([5, -2, 1, -7, -4])

print((4*u) - (3*v))

[ -7 -14  13  45   0]


##### Pythonic Solution to 3.b

In [90]:
import numpy as np
u = np.array([2, -5, 4, 6, -3])
v = np.array([5, -2, 1, -7, -4])
w = np.array([2, 1, -3, 0, 0])

print((5*u) + (2*v) - (2*w))

[ 16 -31  28  16 -23]


##### Pythonic Solution to 3.c

In [91]:
import numpy as np
u = np.array([2, -5, 4, 6, -3])
v = np.array([5, -2, 1, -7, -4])
w = np.array([2, 1, -3,0, 0])

print("u.v = ", u.dot(v))
print("v.w = ", v.dot(w))
print("u.w = ", u.dot(w))

u.v =  -6
v.w =  5
u.w =  -13


##### Pythonic Solution to 3.d

In [92]:
import numpy as np
from numpy.linalg import norm
u = np.array([2, -5, 4, 6, -3])
v = np.array([5, -2, 1, -7, -4])
w = np.array([2, 1, -3])


print('||u||: ', np.sqrt(u.dot(u)))
print('sqrt(90): ', np.sqrt(90))

print('||v||: ', np.sqrt(v.dot(v)))
print('sqrt(95): ', np.sqrt(95))

print('||w||: ', np.sqrt(w.dot(w)))
print('sqrt(14): ', np.sqrt(14))

||u||:  9.486832980505138
sqrt(90):  9.486832980505138
||v||:  9.746794344808963
sqrt(95):  9.746794344808963
||w||:  3.7416573867739413
sqrt(14):  3.7416573867739413


##### Pythonic Solution to 3.e

In [93]:
import numpy as np
from numpy.linalg import norm
u = np.array([2, -5, 4, 6, -3])
v = np.array([5, -2, 1, -7, -4])

print('angle: ', np.dot(u,v)/(np.linalg.norm(u)*np.linalg.norm(v)))
print("angle: ",-6/(np.sqrt(90)*np.sqrt(95)))

angle:  -0.06488856845230502
angle:  -0.06488856845230502


##### Pythonic Solution to 3.f

In [94]:
import numpy as np
from numpy.linalg import norm
v = np.array([5, -2, 1, -7, -4])
w = np.array([2, 1, -3, 0, 0])

print('angle: ', np.dot(v,w)/(np.linalg.norm(v)*np.linalg.norm(w)))
print("angle: ", 5/(np.sqrt(95)*np.sqrt(14)))

angle:  0.13710212427677046
angle:  0.13710212427677046


##### Pythonic Solution to 3.g

In [95]:
import numpy as np
from numpy.linalg import norm
u = np.array([2, -5, 4, 6, -3])
w = np.array([2, 1, -3, 0, 0])

print('angle: ', np.dot(u,w)/(np.linalg.norm(u)*np.linalg.norm(w)))
print("angle: ", -13/(np.sqrt(90)*np.sqrt(14)))

angle:  -0.3662335103823572
angle:  -0.3662335103823572


##### Pythonic Solution to 3.h

In [96]:
import numpy as np
from numpy.linalg import norm
u = np.array([2, -5, 4, 6, -3])
v = np.array([5, -2, 1, -7, -4])

print('d(u,v): ', np.linalg.norm(u - v))

d(u,v):  14.035668847618199


##### Pythonic Solution to 3.i

In [97]:
import numpy as np
from numpy.linalg import norm
v = np.array([5, -2, 1, -7, -4])
w = np.array([2, 1, -3, 0, 0])

print('d(w,v): ', np.linalg.norm(w - v))

d(w,v):  9.9498743710662


##### Pythonic Solution to 3.j

In [98]:
import numpy as np
from numpy.linalg import norm
u = np.array([2, -5, 4, 6, -3])
w = np.array([2, 1, -3, 0, 0])

print('d(u,w): ', np.linalg.norm(u - w))

d(u,w):  11.40175425099138


##### Pythonic Solution to 3.k

In [99]:
import numpy as np
from numpy.linalg import norm
u = np.array([2, -5, 4, 6, -3])
v = np.array([5, -2, 1, -7, -4])

print("proj(u,v): ",u.dot(v)*v/(np.linalg.norm(v)**2) )
print("proj(u,v): ",[30/95,12/95,-6/95,42/95,24/95])

proj(u,v):  [-0.31578947  0.12631579 -0.06315789  0.44210526  0.25263158]
proj(u,v):  [0.3157894736842105, 0.12631578947368421, -0.06315789473684211, 0.4421052631578947, 0.25263157894736843]


##### Pythonic Solution to 3.l

In [100]:
import numpy as np
from numpy.linalg import norm
v = np.array([5, -2, 1, -7, -4])
w = np.array([2, 1, -3, 0, 0])

print("proj(w,v): ",w.dot(v)*v/(np.linalg.norm(v)**2) )
print("proj(w,v): ",[5/19,-2/19,1/19,-7/19,-4/19])

proj(w,v):  [ 0.26315789 -0.10526316  0.05263158 -0.36842105 -0.21052632]
proj(w,v):  [0.2631578947368421, -0.10526315789473684, 0.05263157894736842, -0.3684210526315789, -0.21052631578947367]


##### Pythonic Solution to 3.m

In [101]:
import numpy as np
from numpy.linalg import norm
u = np.array([2, -5, 4, 6, -3])
w = np.array([2, 1, -3, 0, 0])

print("proj(w,v): ",u.dot(w)*w/(np.linalg.norm(w)**2) )
print("proj(w,v): ",[-26/14,-13/14,39/14])

proj(w,v):  [-1.85714286 -0.92857143  2.78571429  0.          0.        ]
proj(w,v):  [-1.8571428571428572, -0.9285714285714286, 2.7857142857142856]


4. Normalize each vector:<br>
$\textbf{u'} = \frac{1}{||\textbf{u}||} \textbf{u} = \frac{\textbf{u}}{|| \textbf{u} ||}$<br><br>
a. $\textbf{u}$ = (5,-7).<br>
    ||$\textbf{u}$|| = $\sqrt{\textbf{u} \cdotp \textbf{u}} = \sqrt{(5)(5) + (-7)(-7)} = \sqrt{74}$<br>
    $\textbf{u'} = \frac{\textbf{u}}{||\textbf{u}||} = (\frac{5}{\sqrt{74}},\frac{7}{\sqrt{74}})$<br>
   
b. $\textbf{v}$ = (1,2,-2,4).<br>
||$\textbf{u}$|| = $\sqrt{\textbf{u} \cdotp \textbf{u}} = \sqrt{(1)(1) + (2)(2) + (-2)(-2) + (4)(4)} = 5$<br>
    $\textbf{u'} = \frac{\textbf{u}}{||\textbf{u}||} = (\frac{1}{5},\frac{2}{5},\frac{-2}{5},\frac{4}{5})$<br>

c. $\textbf{w} = (\frac{1}{2},\frac{-1}{3},\frac{3}{4})$.<br>
||$\textbf{u}$|| = $\sqrt{\textbf{u} \cdotp \textbf{u}} = \sqrt{(\frac{1}{2})(\frac{1}{2}) + (\frac{-1}{3})(\frac{-1}{3}) + (\frac{3}{4})(\frac{3}{4})} = \frac{\sqrt{101}}{12}$<br>


##### Pythonic Solution to 4.a

In [103]:
import numpy as np
from numpy.linalg import norm

u = np.array([5, -7])
print("u': ", u/np.sqrt(u.dot(u)))

u':  [ 0.58123819 -0.81373347]


##### Pythonic Solution to 4.b

In [104]:
import numpy as np
from numpy.linalg import norm
v = np.array([1, 2, -2, 4])
print("v': ", v/np.sqrt(v.dot(v)))

v':  [ 0.2  0.4 -0.4  0.8]


##### Pythonic Solution to 4.c

In [105]:
import numpy as np
from numpy.linalg import norm
w = np.array([1/2, -1/3, 3/4])
print("w': ", np.linalg.norm(w))
print("w': ", np.sqrt(133/144))

w':  0.961046882889233
w':  0.961046882889233


5. Let $\textbf{u} = (1,2,-2)$,$\textbf{v} = (3,-12,4)$ and a scalar $k = -3$: <br>
Find $||u||, ||v||, ||u+v||, ||ku||$.<br>
<br>
$||u|| = \sqrt{u \cdotp u} =\sqrt{1(1) + (2)(2) + (-2)(-2)}=\sqrt{1 + 4 + 4} = \sqrt{9} = 3$<br>
$||v|| = \sqrt{v \cdotp v} =\sqrt{3(3) + (-12)(-12) + (4)(4)}=\sqrt{9 + 144 + 16} = \sqrt{169} = 13$<br>
$||u+v|| = \sqrt{(1+3)^2 + (2+(-12))^2 + ((-2)+4)^2} = \sqrt{16 + 100 + 4} = \sqrt{120}$<br>
$||ku|| = \sqrt{((-3)(1))^2 + ((-3)(2))^2 + ((-3)(-2))^2} = \sqrt{9 + 36 + 36} = \sqrt{81} = 9$<br>


##### Pythonic solution for 5
$ ||u|| $

In [4]:
import numpy as np
from numpy.linalg import norm
u = np.array([1, 2, -2])
v = np.array([3, -12, 4])
k = -3

print("||u||: ", np.linalg.norm(u))

||u||:  3.0


##### Pythonic solution for 5
$ ||v|| $

In [9]:
import numpy as np
from numpy.linalg import norm
v = np.array([3, -12, 4])

print("||v||: ", np.linalg.norm(v))

||v||:  13.0


##### Pythonic solution for 5
$ ||u+v|| $

In [8]:
import numpy as np
from numpy.linalg import norm
u = np.array([1, 2, -2])
v = np.array([3, -12, 4])

print("||u+v||: ", np.linalg.norm(u+v))
print("sqrt(120): ", np.sqrt(120))

||u+v||:  10.954451150103322
sqrt(120):  10.954451150103322


##### Pythonic solution for 5
$ ||ku|| $

In [10]:
import numpy as np
from numpy.linalg import norm
u = np.array([1, 2, -2])
k = -3

print("||ku||: ", np.linalg.norm(k*u))

||ku||:  9.0


6. Find k so that $\textbf{u}  \ and \  \textbf{v}$ are orthogonal.
a. $\textbf{u} = (3, k, -2), \textbf{v} = (6, -4, -3)$.<br>

$0 = u(v) = u_1(v_1)+u_2(v_2)+u_3(v_3)$<br>
$0 = 3(6)+ k(-4) + -2(-3) = 18 -4k + 6$<br>
$4k = 18 + 6$ <br>
$k = \frac{24}{4}$ <br>
$k = 6$

<br>
b. $\textbf{u} = (5,k,-4,2), \textbf{v} = (1,-3,2,2k)$.<br>

$0 = u(v) = u_1(v_1)+u_2(v_2)+u_3(v_3)$<br>
$0 = 5(1)+ k(-3) + -4(2) + 2(2k)= 5 + (-3k) + (-8) + 4k$<br>
$4k - 3k = 8 - 5$ <br>
$k = 3$ <br>

c. $\textbf{u} = (1,7,k+2,-2), \textbf{v} = (3, k, -3,k)$.<br>

$0 = u(v) = u_1(v_1)+u_2(v_2)+u_3(v_3)$<br>
$0 = 1(3)+ 7(k) + k+2(-3) + -2(k)= 3 + 7k - 3k - 6 -2k$<br>
$7k - 3k - 2k = 6 - 3$ <br>
$2k = 3$ <br>
$k = \frac{3}{2} = 1.5$

##### Pythonic solution for 6.a

In [15]:
import numpy as np
from numpy.linalg import norm
k = 6
u = np.array([3, k, -2])
v = np.array([6, -4, -3])

print("u*v: ", u.dot(v))

u*v:  0


##### Pythonic solution for 6.b

In [16]:
import numpy as np
from numpy.linalg import norm
k = 3
u = np.array([5, k, -4, 2])
v = np.array([1, -3, 2, 2*k])

print("u*v: ", u.dot(v))

u*v:  0


##### Pythonic solution for 6.c

In [22]:
import numpy as np
from numpy.linalg import norm
k = 1.5
u = np.array([1, 7, k+2, -2])
v = np.array([3, k, -3, k])

print("u*v: ", u.dot(v))

u*v:  0.0
