Linear Transformation Assignment
<br />
Lara R. Jakosalem
<br />

---

$\textbf{Code Challenges}$

1. Develop a python function from scratch that will find the determinants of any $n \times n$ matrix.

2. Develop a python function from scratch that will find both the eigenvectors and eigenvalues of any $n \times n$ matrix.

3. Test your functions from a randomly generated $n \times n$ matrix.

**NUMBER 1**

In [58]:
def get_determinant(m):
    if len(m) == 0 or len(m) != len(m[0]):
        raise ValueError("Invalid. Matrix must be square.")
    n = len(m)
    if n == 1:
        return m[0][0]
    det = 0
    for col in range(n):
        sub_matrix = [row[:col] + row[col+1:] for row in m[1:]]
        sub_det = get_determinant(sub_matrix)
        sign = (-1) ** col
        det += m[0][col] * sub_det * sign
    pass
    return det

Note: Only using numpy for the test case, no libraries were used in the function

In [59]:
import numpy as np
import random

n = random.randint(1, 6)
random_matrix = np.random.randint(-10, 11, size=(n, n)).tolist()

determinant = get_determinant(random_matrix)

print("Randomly generated matrix:")
print(np.array(random_matrix)) 
print("Determinant:", determinant)

Randomly generated matrix:
[[ -9  -2  -6   2]
 [ -1  -5 -10  -7]
 [ -1  -4  -9  -7]
 [  3   8   1  -5]]
Determinant: -364


**NUMBER 2**

In [68]:
def get_eigenvaluesvectors(m, iterations=100, tolerance=1e-10):
    n = len(m)
    eigenvalues = []
    eigenvectors = []

    def matrix_multiplication(m, v):
        n = len(m)
        result = [0] * n
        for i in range(n):
            for j in range(n):
                result[i] += m[i][j] * v[j]
        return result

    def dot_product(v1, v2):
        return sum(a * b for a, b in zip(v1, v2))

    def normalize_vector(v):
        norm = sum(x**2 for x in v)**0.5
        return [x / norm for x in v]
        
    initial_vector = [1] * n
    for _ in range(iterations):
        new_vector = matrix_multiplication(m, initial_vector)
        eigenvalue = dot_product(new_vector, initial_vector)
        new_vector = normalize_vector(new_vector)
        norm_difference = sum((x - y) ** 2 for x, y in zip(new_vector, initial_vector)) ** 0.5
        if norm_difference < tolerance:
            break      
        initial_vector = new_vector
    eigenvalues.append(eigenvalue)
    eigenvectors.append(new_vector)

    return eigenvalues, eigenvectors

In [69]:
import numpy as np

def generate_random_matrix(n):
    return np.random.randint(1, 10, size=(n, n))
    
n = np.random.randint(2, 7)
new_matrix = generate_random_matrix(n)

# Calculate eigenvalues and eigenvectors for the generated matrix
eigenvalues, eigenvectors = get_eigenvaluesvectors(new_matrix)
print("Generated Matrix:")
print(new_matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Generated Matrix:
[[5 9 3 9 3 6]
 [3 8 9 6 3 1]
 [4 8 3 7 7 3]
 [1 7 2 5 9 2]
 [9 3 2 6 8 3]
 [6 4 1 3 4 1]]
Eigenvalues: [29.403604356229472]
Eigenvectors: [[0.4680448729202483, 0.4285560912641462, 0.444491691796024, 0.36285132094850847, 0.43866822620378, 0.2749725726375733]]
