Systems of Linear Equations Assignment
<br /><br />
Lara R. Jakosalem

---

In [5]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    pass
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    pass
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale

    pass
    return B

---

**ASSIGNMENT 1**<br />
Backwards Substitution

In [15]:
import numpy as np
A = np.array([[1,-1,1,3],[0,1,2,4],[0,0,1,2],[0,0,0,0],[0,0,0,0]]) 

def BackwardSubstitution(A):
    m, n = A.shape 
    while m > 0 and np.all(A[m-1, n-2:] == 0):
        m -= 1
    if m == 0:
        return "There is no solution."
    elif n - 1 > m:
        return "There are infinite solutions."
    solutions = np.zeros(m)
    for j in range(m - 1, -1, -1):
        r_coefficients = A[j, :-1]
        constants = A[j, -1]
        if np.all(r_coefficients == 0):
            return "There are no solutions."
        result = np.dot(solutions, r_coefficients)
        solutions[j] = (constants - result) / r_coefficients[j]
    pass
    return solutions

Use Backsubstitution with Example

In [16]:
# using pythonic solutions
import numpy as np
A=np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])

## Add -2 times row 0 to row 1
A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1,'\n')

## Add -4 times row 0 to row 2
A2 = RowAdd(A1,0,2,-4)
print("A2")
print(A2,'\n')

## Add -2 times row 1 to row 2
A3 = RowAdd(A2,1,2,-2)
print("A3")
print(A3,'\n')

## Multiply row 1 by 1/3
A4 = RowScale(A3,1,1.0/3)
print("A4")
print(A4,'\n')

## Multiply row 2 by 1/19
A5 = RowScale(A4,2,1.0/-19.)
print("A5")
print(A5,'\n')
print("Use your assignment for the backward substitution to find the solutions.")

## Assignment 1
print("Solutions x_1, x_2, x_3:")
print(BackwardSubstitution(A5))

A1
[[ 1. -1.  1.  3.]
 [ 0.  3.  6. 12.]
 [ 4.  2. -3. -2.]] 

A2
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   6.  -7. -14.]] 

A3
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   0. -19. -38.]] 

A4
[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   0. -19. -38.]] 

A5
[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]] 

Use your assignment for the backward substitution to find the solutions.
Solutions x_1, x_2, x_3:
[1. 0. 2.]


---

**ASSIGNMENT 2**<br />


**NUMBER 1**


1. Provide reasons why each of the following equations is, or is not, a linear equation.
- $\cos{\theta}x+4y+z = \sqrt{3}$ <br />
Not linear because it contains a trigonometric function cos $\cos{\theta}$ which does not fit the definition of linear equation where x, y, z are linear without non-linear or trigonometric functions.
- $cos{x}4y+z = \sqrt{3}$ <br />
Not linear because it contains a trigonometric function cos x multiplied by 4y and combined with z.
- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$ <br />
Not linear because it has an exponent of -1. Exponents in linear equations should only be 1.
- $x^1+y^1+z^1=0$ <br />
Linear because it all variables x, y, z are raised to the power of 1 which fits the definition of linear equation.
---
**NUMBER 2**<br />
2. Find the solutions to the linear equations:
- $2x_1+3x_2 =5$ <br />
  $$2x_1 + 3x_2 = 5 \implies x_1 = \frac{5 - 3x_2}{2}$$
- $4x_1+3x_2+2x_3=1$ <br />
  $$4x_1 + 3x_2 + 2x_3 = 1 \implies x_3 = \frac{1 - 4x_1 - 3x_2}{2}$$
- $3x-6y=0$ <br />
  $$3x - 6y = 0 \implies x = 2y$$

**PYTHONIC SOLUTION TO NUMBER 2**

In [4]:
import sympy as sp

x1, x2 = sp.symbols('x1 x2')
equation_1 = sp.Eq(2*x1 + 3*x2, 5)
solution_1 = sp.solve(equation_1, (x1, x2))

print("Equation 1 Result: ")
print(solution_1)

Equation 1 Result: 
[(5/2 - 3*x2/2, x2)]


In [1]:
import sympy as sp

x1, x2, x3 = sp.symbols('x1 x2 x3')
equation_2 = sp.Eq(4*x1 + 3*x2 + 2*x3, 1)
solution_2 = sp.solve(equation_2, (x1, x2, ))

print("Equation 2 Result: ")
print(solution_2)

Equation 2 Result: 
[(-3*x2/4 - x3/2 + 1/4, x2)]


In [3]:
import sympy as sp

x, y = sp.symbols('x y')
equation_3 = sp.Eq(3*x - 6*y, 0)
solution_3 = sp.solve(equation_3, x)

print("Equation 3 Result: ")
print(solution_3)

Equation 3 Result: 
[2*y]


---

**NUMBER 3**


3. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x-y=0 \\
2x+y = 3
\end{equation}
<br>
<br>
b. <br>
\begin{equation}
x+5y= -1 \\
-x+y = -5 \\
2x+4y = 4
\end{equation}
c. <br>
\begin{equation}
2x_1+3x_2-x_3= -1 \\
x_1+x_3 = 0 \\
-x_1+2x_2-2x_3 = 0
\end{equation}
<br>--

### Manual Solutions:

**Manual Solution 3.a**
$$
\begin{align*}
-2(x - y &= 0) \\
-2x + 2y &= 0 \quad + \quad 2x + y = 3 \\
= \frac{3y}{3} &= \frac{3}{3} \\
y &= 1 \\
\end{align*}
$$

$$
\begin{align*}
x - 1 &= 0 \\
x &= 1 \\
\end{align*}
$$

**Manual Solution 3.b**
$$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    -1 & 1 &\bigm| & -5 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\frac{1}{6}\text{R}_{2}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 5\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 4 \\
    0 & 1 &\bigm| & -1 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 6\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 4 \\
    0 & 1 &\bigm| & -1 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$$

$$
\begin{align*}
x &= 4 + 0t, x = 4 \\
y &= -1 + 0t, y = -1 \\
\end{align*}
$$

**Manual Solution 3.c**
$$
\begin{pmatrix}
    2 & 3 & -1 &\bigm| & -1 \\
    1 & 0 & 1 &\bigm| & 0 \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    1 & 0 & 1 &\bigm| & 0 \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & \frac{-3}{2} & \frac{3}{2} &\bigm| & \frac{1}{2} \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & \frac{-3}{2} & \frac{3}{2} &\bigm| & \frac{1}{2} \\
    0 & \frac{7}{2} & \frac{-5}{2} &\bigm| & \frac{-1}{2} \\
\end{pmatrix}
\xrightarrow{\frac{-2}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & \frac{7}{2} & \frac{-5}{2} &\bigm| & \frac{-1}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \frac{7}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{3}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{1}{3} &\bigm| & \frac{1}{3} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
$$

$$
\begin{align*}
x_1 &= 0 \\
x_3 &= -\frac{5}{9} \\
x_2 - x_3 &= -\frac{1}{3} \\
x_2 - (-\frac{5}{9}) &= -\frac{1}{3} \\
x_2 &= -\frac{1}{3} - \frac{5}{9} \\
x_2 &= -\frac{8}{9} \\
\end{align*}
$$

**PYTHONIC SOLUTION 3.A**

In [3]:
import numpy as np

# Define the matrix A and vector b
A = np.array([[1, -1],
              [2, 1]])
b = np.array([0, 3])

# Perform row operation: Row 2 = Row 2 - 2 * Row 1
A[1] = A[1] - 2 * A[0]

# Solve the system
solution = np.linalg.solve(A, b)

# Print the solution
print("Solution:")
print(solution)


Solution:
[1. 1.]


**PYTHONIC SOLUTION 3.B**

In [17]:
import numpy as np
A=np.array([[1,5,-1],[-1,1,-5],[2,4,4]])

A1 = RowAdd(A,0,1,1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,2,-2)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,1,1/6)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,-5)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,2,6)
print("A5")
print(A5,'\n')

print("Solutions x, y")
print(BackwardSubstitution(A5))

A1
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 2.  4.  4.]] 

A2
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 0. -6.  6.]] 

A3
[[ 1.  5. -1.]
 [ 0.  1. -1.]
 [ 0. -6.  6.]] 

A4
[[ 1.  0.  4.]
 [ 0.  1. -1.]
 [ 0. -6.  6.]] 

A5
[[ 1.  0.  4.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]] 

Solutions x, y
[ 4. -1.]


**PYTHONIC SOLUTION 3.C**

In [20]:
import numpy as np
A=np.array([[2,3,-1,-1],[1,0,1,0],[-1,2,-2,0]])

A1 = RowScale(A,0,1/2)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,1,-1)
print("A2")
print(A2,'\n')
A3 = RowAdd(A2,0,2,1)
print("A3")
print(A3,'\n')
A4 = RowScale(A3,1,-2/3)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,0,-3/2)
print("A5")
print(A5,'\n')
A6 = RowAdd(A5,1,2,-7/2)
print("A6")
print(A6,'\n')
A7 = RowAdd(A6,2,0,-1)
print("A7")
print(A7,'\n')
A8 = RowAdd(A7,2,1,1)
print("A8")
print(A8,'\n')

print("Solutions for x1, x2, x3:")
print(BackwardSubstitution(A8))

A1
[[ 1.   1.5 -0.5 -0.5]
 [ 1.   0.   1.   0. ]
 [-1.   2.  -2.   0. ]] 

A2
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [-1.   2.  -2.   0. ]] 

A3
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [ 0.   3.5 -2.5 -0.5]] 

A4
[[ 1.          1.5        -0.5        -0.5       ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          3.5        -2.5        -0.5       ]] 

A5
[[ 1.          0.          1.          0.        ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          3.5        -2.5        -0.5       ]] 

A6
[[ 1.          0.          1.          0.        ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

A7
[[ 1.          0.          0.         -0.66666667]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

A8
[[ 1.          0.          0.         -0.66666667]
 [ 0.          1.          0.          0.33333333]
 [ 0.          0.          1.     

---

**NUMBER 4**


4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or niether both.<br>
a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br><br>
b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br><br>
c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br><br>
d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br><br>
e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br><br>
f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br><br>
g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br><br>
h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}
<br><br>


**Explanation** <br />
a. Matrix is neither both because the non-zero in the bottom row is not to the very right.
<br />
b. Matrix is in row-echelon form because all zero rows are at the bottom, and the leading entry in each non-zero row is to the right of the leading entry in the row.
<br />
c. The matrix is in row-echelon form because all zero rows are at the bottom, and the leading entry of a non-zero row is to the right of the leading entry above it.
<br />
d. Matrix is in row-echelon form. No non-zeroes so it doesn't violate the row-echelon form definition.
<br />
e. Matrix is not in row echelon form because the zero row is not at the bottom. Non-zero row is at the bottom instead.
<br />
f. Matrix is in reduced row echelon form because all leading entries are 1, and are between 0s.
<br />
g. Matrix is in row echelon form because all zero rows are at the bottom, and leading entries are to the right of the leading entries on top of them.
<br />
h. Matrix is in row echelon form because all leading entries are to the right of the leading entries above it, and the all zero row is at the bottom.

---

**NUMBER 5**

**Manual solution 5.a**

Manual Solution:

\[
\begin{align*}
\begin{pmatrix}
    1 & 2 & -3 & \big| & 9 \\
    2 & -1 & -1 & \big| & 0 \\
    4 & -1 & 1 & \big| & 4 \\
\end{pmatrix}
&\xrightarrow{R_{2} - 2R_{1}}
\begin{pmatrix}
    1 & 2 & -3 & \big| & 9 \\
    0 & -5 & 5 & \big| & -18 \\
    4 & -1 & 1 & \big| & 4 \\
\end{pmatrix} \\
&\xrightarrow{R_{3} - 4R_{1}}
\begin{pmatrix}
    1 & 2 & -3 & \big| & 9 \\
    0 & -5 & 5 & \big| & -18 \\
    0 & -9 & 13 & \big| & -32 \\
\end{pmatrix} \\
&\xrightarrow{-\frac{1}{5}R_{2}}
\begin{pmatrix}
    1 & 2 & -3 & \big| & 9 \\
    0 & 1 & -1 & \big| & \frac{18}{5} \\
    0 & -9 & 13 & \big| & -32 \\
\end{pmatrix} \\
&\xrightarrow{R_{3} - 9R_{2}}
\begin{pmatrix}
    1 & 2 & -3 & \big| & 9 \\
    0 & 1 & -1 & \big| & \frac{18}{5} \\
    0 & 0 & 4 & \big| & -\frac{2}{5} \\
\end{pmatrix}
\end{align*}
\]

\[
\begin{align*}
x_1 + 2x_2 - 3x_3 &= 9 \\
x_2 - x_3 &= \frac{18}{5} \\
4x_3 &= -\frac{2}{5}
\end{align*}
\]

\[
\begin{align*}
x_3 &= \frac{1}{10} \\
x_2 &= \frac{37}{10} \\
x_1 &= \frac{19}{10}
\end{align*}
\]


**Manual solution 5.b**

$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    2 & 1 & 1 &\bigm| & 1 \\
    -1 & 1 & -1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1 &\bigm| & 3 \\
    -1 & 1 & -1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1 &\bigm| & 3 \\
    0 & 3 & -1 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1 &\bigm| & 3 \\
    0 & 0 & 0 &\bigm| & 1 \\
\end{pmatrix}
$

\(L3: 0z = 1\) not possible

**Manual solution 5.c**

$
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    -1 & 2 & 1 &\bigm| & 0 \\
    2 & 4 & 6 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    2 & 4 & 6 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    0 & 10 & 10 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 10\text{R}_{2}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    0 & 0 & 0 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 3\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$
<br><br>
L1: x1 + x3 = 0 = x1 + -x3<br>
L2: x2 + x3 = 0 = x2 = -x3<br>
L3: 0x1 + 0x2 + 0x3 = 0<br>
x3 is of any value for L3 since the result is 0

**Manual Solution 5.d**
<br />
<br />
$$
\begin{align*}
w + x + 2y + z &= 1 \\
w - x - y + z &= 0 \\
x + y &= 1 \\
w + x + z &= 2
\end{align*}\\
$$
<br><br>
$
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
1 & -1 & -1 & 1 & \big| & 0 \\
0 & 1 & 1 & 0 & \big| & 1 \\
1 & 1 & 0 & 1 & \big| & 2 \\
\end{bmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 1 & 1 & 0 & \big| & 1 \\
1 & 1 & 0 & 1 & \big| & 2 \\
\end{bmatrix}
\xrightarrow{\text{R}_{3} + 2\text{R}_{2}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 0 & 1 & 0 & \big| & 1 \\
1 & 1 & 0 & 1 & \big| & 2 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} + \text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 0 & 1 & 0 & \big| & 1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{-1\text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 2 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 2 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - 2\text{R}_{3}}
\begin{bmatrix}
1 & 1 & 0 & 1 & \big| & 4 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{-\frac{1}{2}\text{R}_{2}}
\begin{bmatrix}
1 & 1 & 0 & 1 & \big| & 4 \\
0 & 1 & -\frac{1}{2} & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{bmatrix}
1 & 0 & \frac{1}{2} & 1 & \big| & \frac{9}{2} \\
0 & 1 & -\frac{1}{2} & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{1}}
\begin{bmatrix}
1 & 0 & \frac{1}{2} & 1 & \big| & \frac{9}{2} \\
0 & 1 & -\frac{1}{2} & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
0 & 0 & 1 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{4}}
\begin{bmatrix}
1 & 0 & 0 & 0 & \big| & 0 \\
0 & 1 & 0 & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
0 & 0 & 1 & 1 & \big| & 4 \\
\end{bmatrix}
$

$$
\begin{align*}
w &= 0 \\
x &= -\frac{1}{2} \\
y &= -1 \\
z &= 0 \\
\end{align*}
$$

<br />

**PYTHONIC SOLUTION 5.A**

In [24]:
#5.A
import numpy as np
A=np.array([[1,2,-3,9],
            [2,-1,-1,0],
            [4,-1,1,4]])

A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,2,-4)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,1,-1/5)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,-2)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,2,9)
print("A5")
print(A5,'\n')
A6 = RowScale(A5,2,1/4)
print("A6")
print(A6,'\n')
A7 = RowAdd(A6,2,0,1)
print("A7")
print(A7,'\n')
A8 = RowAdd(A7,2,1,1)
print("A8")
print(A8,'\n')

print("Solutions to vectors x1, x2, x3:")
print(BackwardSubstitution(A8))

A1
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  4.  -1.   1.   4.]] 

A2
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  0.  -9.  13. -32.]] 

A3
[[  1.    2.   -3.    9. ]
 [ -0.    1.   -1.    3.6]
 [  0.   -9.   13.  -32. ]] 

A4
[[  1.    0.   -1.    1.8]
 [ -0.    1.   -1.    3.6]
 [  0.   -9.   13.  -32. ]] 

A5
[[ 1.   0.  -1.   1.8]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   4.   0.4]] 

A6
[[ 1.   0.  -1.   1.8]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   1.   0.1]] 

A7
[[ 1.   0.   0.   1.9]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   1.   0.1]] 

A8
[[1.  0.  0.  1.9]
 [0.  1.  0.  3.7]
 [0.  0.  1.  0.1]] 

Solutions to vectors x1, x2, x3:
[1.9 3.7 0.1]


**PYTHONIC SOLUTION 5.B**

In [27]:
# 5.B
import numpy as np
A=np.array([[1,2,0,-1],
            [2,1,1,1],
            [-1,1,-1,-1]])

A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,2,1)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,1,-1/3)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,-2)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,2,-3)
print("A5")
print(A5,'\n')

solutions = BackwardSubstitution(A5)

print("Solutions to vectors x, y, z:")
print(solutions)
print("because  0x + 0y + 0z != 1")

A1
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [-1.  1. -1. -1.]] 

A2
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  3. -1. -2.]] 

A3
[[ 1.          2.          0.         -1.        ]
 [-0.          1.         -0.33333333 -1.        ]
 [ 0.          3.         -1.         -2.        ]] 

A4
[[ 1.          0.          0.66666667  1.        ]
 [-0.          1.         -0.33333333 -1.        ]
 [ 0.          3.         -1.         -2.        ]] 

A5
[[ 1.          0.          0.66666667  1.        ]
 [-0.          1.         -0.33333333 -1.        ]
 [ 0.          0.          0.          1.        ]] 

Solutions to vectors x, y, z:
There are no solutions.
because  0x + 0y + 0z != 1


**PYTHONIC SOLUTION 5.C**

In [33]:
# 5.C
import numpy as np
A=np.array([[1,-3,-2,0],[-1,2,1,0],[2,4,6,0]])
A1 = RowAdd(A,0,1,1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,2,-2)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,1,-1)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,3)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,2,-10)
print("A5")
print(A5,'\n')

solutions = BackwardSubstitution(A5)

print("Solutions to vectors x1, x2, x3:")
print(solutions)

A1
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 2.  4.  6.  0.]] 

A2
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0. 10. 10.  0.]] 

A3
[[ 1. -3. -2.  0.]
 [-0.  1.  1. -0.]
 [ 0. 10. 10.  0.]] 

A4
[[ 1.  0.  1.  0.]
 [-0.  1.  1. -0.]
 [ 0. 10. 10.  0.]] 

A5
[[ 1.  0.  1.  0.]
 [-0.  1.  1. -0.]
 [ 0.  0.  0.  0.]] 

Solutions to vectors x1, x2, x3:
There are infinite solutions.


**PYTHONIC SOLUTION 5.D**

In [30]:
# 5.D
import numpy as np
A=np.array([[1,1,2,1,1],[1,-1,-1,1,0],[0,1,1,0,1],[1,1,0,1,2]])
A1 = RowAdd(A,0,1,-1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,3,-1)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,1,-1/2)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,-1)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,2,-1)
print("A5")
print(A5,'\n')
A6 = RowScale(A5,2,-2)
print("A6")
print(A6,'\n')
A7 = RowAdd(A6,2,0,-1/2)
print("A7")
print(A7,'\n')
A8 = RowAdd(A7,2,1,-3/2)
print("A8")
print(A8,'\n')
A9 = RowAdd(A8,2,3,2)
print("A9")
print(A9,'\n')

solutions = BackwardSubstitution(A9)

print("Solutions to vectors x1, x2, x3:")
print(solutions)

A1
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0.  1.  1.  0.  1.]
 [ 1.  1.  0.  1.  2.]] 

A2
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0.  1.  1.  0.  1.]
 [ 0.  0. -2.  0.  1.]] 

A3
[[ 1.   1.   2.   1.   1. ]
 [-0.   1.   1.5 -0.   0.5]
 [ 0.   1.   1.   0.   1. ]
 [ 0.   0.  -2.   0.   1. ]] 

A4
[[ 1.   0.   0.5  1.   0.5]
 [-0.   1.   1.5 -0.   0.5]
 [ 0.   1.   1.   0.   1. ]
 [ 0.   0.  -2.   0.   1. ]] 

A5
[[ 1.   0.   0.5  1.   0.5]
 [-0.   1.   1.5 -0.   0.5]
 [ 0.   0.  -0.5  0.   0.5]
 [ 0.   0.  -2.   0.   1. ]] 

A6
[[ 1.   0.   0.5  1.   0.5]
 [-0.   1.   1.5 -0.   0.5]
 [-0.  -0.   1.  -0.  -1. ]
 [ 0.   0.  -2.   0.   1. ]] 

A7
[[ 1.   0.   0.   1.   1. ]
 [-0.   1.   1.5 -0.   0.5]
 [-0.  -0.   1.  -0.  -1. ]
 [ 0.   0.  -2.   0.   1. ]] 

A8
[[ 1.  0.  0.  1.  1.]
 [ 0.  1.  0.  0.  2.]
 [-0. -0.  1. -0. -1.]
 [ 0.  0. -2.  0.  1.]] 

A9
[[ 1.  0.  0.  1.  1.]
 [ 0.  1.  0.  0.  2.]
 [-0. -0.  1. -0. -1.]
 [ 0.  0.  0.  0. -1.]] 

Solutions to vecto

---

**NUMBER 6**

6. Determine if the vectors are linear combinations<br>
a. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} -1 \\ 3 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\
\end{equation}
<br><br>
b. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br><br>
c. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br><br>


**Manual Solution 6.a**

<br>

$
x \textbf{u}_2 + y \textbf{u}_3 = \textbf{v} \\
\begin{align*}
-x + 2y &= 1 \\
3x - 6y &= 2
\end{align*}
$

<br>

$
\begin{bmatrix}
-1 & 2 & | & 1 \\
3 & -6 & | & 2
\end{bmatrix}
\xrightarrow{\text{R}_{2} + 3\text{R}_{1}}
\begin{bmatrix}
-1 & 2 & | & 1 \\
0 & 0 & | & 5
\end{bmatrix}
$

- The system doesn't hold as the final row implies an incorrect equation, 0 equals 5. Hence, vector v cannot be formed by combining u2 and u3.


**Manual Solution 6.B**

<br>
$$
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    1 & 1 &\bigm| & 2 \\
    0 & 1 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 1 &\bigm| & 3 \\
\end{pmatrix}
$$
<br>
<br>
$$
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 1 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 0 &\bigm| & 2 \\
\end{pmatrix}
$$



<br>

- Given x equals 1 and y equals 1, it confirms that the vector can be expressed as a combination of the provided vectors.

**Manual Solution 6.C**

$$
\begin{bmatrix}
1 & 0 & | & 3 \\
1 & 1 & | & 1 \\
0 & 1 & | & -2
\end{bmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{bmatrix}
1 & 0 & | & 3 \\
0 & 1 & | & -2 \\
0 & 1 & | & -2
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{bmatrix}
1 & 0 & | & 3 \\
0 & 1 & | & -2 \\
0 & 0 & | & 0
\end{bmatrix}
$$

<br />
- The system is consistent with infinite number of solutions. vector v can be formed by combining u2 and u3, resulting in multiple solutions for x and y.

---

**NUMBER 7**

**Manual Solution 7.a**

$$
\begin{bmatrix}
1 & 1 & | & x \\
1 & -1 & | & y
\end{bmatrix}
\xrightarrow{}
\begin{bmatrix}
\begin{array}{cccc|c}
1 & 1 & | & x & (R_1) \\
1 & -1 & | & y & (R_2)
\end{array}
\end{bmatrix}
\xrightarrow{\text{R}_{2} -\text{R}_{1}}
\begin{bmatrix}
\begin{array}{cccc|c}
1 & 1 & | & x & (R_1) \\
0 & -2 & | & y - x & (R_2 - R_1)
\end{array}
\end{bmatrix}
\xrightarrow{\frac{1}{-2}\text{R}_{2}}
\begin{bmatrix}
\begin{array}{cccc|c}
1 & 1 & | & x & (R_1) \\
0 & 1 & | & \frac{y - x}{-2} & \left(\frac{1}{-2}\right)R_2
\end{array}
\end{bmatrix}
$$ 

The given vectors are a span.

**Manual Solution 7.b**

$$
a + b = x, b + c = y, a + c = z
$$

$$
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
1 & 0 & 1 & | & z
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
0 & -1 & 1 & | & z - x
\end{bmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
0 & 0 & 2 & | & y - x + z
\end{bmatrix}
$$ 

The given vectors are a span.

**Manual Solution 7.C**

$$
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    1 & 0 & 1 &\bigm| & c \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 2 &\bigm| & -a+b+c \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 2 &\bigm| & -a+b+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{a-b+c}{2}  \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & \frac{-a+b+c}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{a-b+c}{2}  \\
    0 & 1 & 1 &\bigm| & \frac{a+b-c}{2} \\
    0 & 0 & 1 &\bigm| & \frac{-a+b+c}{2} \\
\end{pmatrix}
$$

The given vectors are a span.

---

**NUMBER 8**

8. Show that the following vectors are linearly independent:<br>
a. <br>
\begin{equation}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{equation}
b. <br>
\begin{equation}
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\end{equation}
<br>
c. <br>
\begin{equation}
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\end{equation}

**MANUAL SOLUTION 8.A**

$
\begin{pmatrix}
    3 & -1 & 1 & -1 &\bigm| & 0 \\
    -1 & 2 & 1 & -1 &\bigm| & 0 \\
    1 & 1 & 3 & 1 &\bigm| & 0 \\
    -1 & -1 & 1 & 3 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{1}}
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    -1 & 2 & 1 & -1 &\bigm| & 0 \\
    1 & 1 & 3 & 1 &\bigm| & 0 \\
    -1 & -1 & 1 & 3 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    0 & \frac{5}{3} & \frac{4}{3} & -\frac{4}{3} &\bigm| & 0 \\
    1 & 1 & 3 & 1 &\bigm| & 0 \\
    -1 & -1 & 1 & 3 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    0 & \frac{5}{3} & \frac{4}{3} & -\frac{4}{3} &\bigm| & 0 \\
    0 & \frac{4}{3} & \frac{8}{3} & \frac{4}{3} &\bigm| & 0 \\
    -1 & -1 & 1 & 3 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} + \text{R}_{1}}
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    0 & \frac{5}{3} & \frac{4}{3} & -\frac{4}{3} &\bigm| & 0 \\
    0 & \frac{4}{3} & \frac{8}{3} & \frac{4}{3} &\bigm| & 0 \\
    0 & -\frac{4}{3} & \frac{4}{3} & \frac{8}{3} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{3}{5}\text{R}_{2}}
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & \frac{4}{3} & \frac{8}{3} & \frac{4}{3} &\bigm| & 0 \\
    0 & -\frac{4}{3} & \frac{4}{3} & \frac{8}{3} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{3}{5} & -\frac{3}{5} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & \frac{4}{3} & \frac{8}{3} & \frac{4}{3} &\bigm| & 0 \\
    0 & -\frac{4}{3} & \frac{4}{3} & \frac{8}{3} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \frac{4}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{3}{5} & -\frac{3}{5} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & 0 & \frac{8}{5} & \frac{12}{5} &\bigm| & 0 \\
    0 & -\frac{4}{3} & \frac{4}{3} & \frac{8}{3} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} + \frac{4}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{3}{5} & -\frac{3}{5} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & 0 & \frac{8}{5} & \frac{12}{5} &\bigm| & 0 \\
    0 & 0 & \frac{12}{5} & \frac{8}{5} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{5}{8}2\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & \frac{3}{5} & -\frac{3}{5} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & \frac{12}{5} & \frac{8}{5} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{3}{5}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & -\frac{3}{2} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & \frac{12}{5} & \frac{8}{5} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \frac{4}{5}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & -\frac{3}{2} &\bigm| & 0 \\
    0 & 1 & 0 & -2 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & \frac{12}{5} & \frac{8}{5} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} - \frac{12}{5}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & -\frac{3}{2} &\bigm| & 0 \\
    0 & 1 & 0 & -2 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & 0 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{2}\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & -\frac{3}{2} &\bigm| & 0 \\
    0 & 1 & 0 & -2 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \frac{3}{2}\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & -2 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + 2\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \frac{3}{2}\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 0 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$

- The RREF shows that the last column are all zeroes which indicates that the vectors are linearly independent.


**MANUAL SOLUTION 8.B**

$
\begin{pmatrix}
    0 & 0 & 0 & 4 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 2 & 2 & 2 &\bigm| & 0 \\
    1 & 1 & 1 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} \leftrightarrow \text{R}_{4}}
\begin{pmatrix}
    1 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 2 & 2 & 2 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} \leftrightarrow \text{R}_{3}}
\begin{pmatrix}
    1 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 2 & 2 & 2 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{4}\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 0 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$

- The RREF last row are all zeroes except the last column which shows that the vectors are linearly independent.


**MANUAL SOLUTION 8.C**

Performing row operations to row-reduce this matrix:
$$
\begin{pmatrix}
    1 & -1 & 1 & 0 &\bigm| & 0 \\
    -1 & 1 & 0 & 1 &\bigm| & 0 \\
    1 & 0 & 1 & -1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 1 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    1 & 0 & 1 & -1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 1 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} \leftrightarrow \text{R}_{3}}
\begin{pmatrix}
    1 & -1 & 1 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 & -1 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 & -1 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & -1 & 2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & -2 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & -1 & 2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & -2 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 3 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & -2 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + 2\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 0 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$$

- The  RREF shows that the last row has a non-zero entryin the last column which means that the vectors are linearly independent.
